openapi: 3.0.0
info:
  title: Straw hat boiler-plate specs
  description: For straw hat hackers
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/CHRISMADUFOR_1/hng-test-2/1
  description: Straw hat boiler plate live!
