openapi: 3.0.0
info:
  title: Straw hat boiler-plate specs
  description: For straw hat hackers
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/CHRISMADUFOR_1/hng-test-2/1
  description: Straw hat boiler plate live!
paths:
  /auth/login:
    post:
      tags:
      - Auth
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_login_body'
        required: true
      responses:
        "200":
          description: Successful login
        "401":
          description: Invalid credentials
  /auth/register:
    post:
      tags:
      - Auth
      summary: User registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_register_body'
        required: true
      responses:
        "201":
          description: User registered successfully
  /auth/social:
    post:
      tags:
      - Auth
      summary: Social authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_social_body'
        required: true
      responses:
        "200":
          description: Successful authentication
  /auth/magic-link:
    post:
      tags:
      - Auth
      summary: Magic link authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_magiclink_body'
        required: true
      responses:
        "200":
          description: Magic link sent
  /auth/change-password:
    post:
      tags:
      - Auth
      summary: Change password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth_changepassword_body'
        required: true
      responses:
        "200":
          description: Password changed successfully
  /messaging/email:
    post:
      tags:
      - Messaging
      summary: Send an email
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/messaging_email_body'
        required: true
      responses:
        "200":
          description: Email sent
  /payments/stripe:
    post:
      tags:
      - Payments
      summary: Stripe payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payments_stripe_body'
        required: true
      responses:
        "200":
          description: Payment successful
  /payments/flutterwave:
    post:
      tags:
      - Payments
      summary: Flutterwave payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payments_flutterwave_body'
        required: true
      responses:
        "200":
          description: Payment successful
  /payments/lemonsqueezy:
    post:
      tags:
      - Payments
      summary: LemonSqueezy payment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payments_lemonsqueezy_body'
        required: true
      responses:
        "200":
          description: Payment successful
  /users:
    get:
      tags:
      - Users
      summary: Get list of users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
  /users/{id}:
    get:
      tags:
      - Users
      summary: Get a user by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: A single user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "404":
          description: User not found
  /organizations:
    get:
      tags:
      - Organizations
      summary: Get list of organizations
      responses:
        "200":
          description: A list of organizations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
  /organizations/{id}:
    get:
      tags:
      - Organizations
      summary: Get an organization by ID
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: A single organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "404":
          description: Organization not found
  /payments:
    get:
      tags:
      - Payments
      summary: Get list of payments
      responses:
        "200":
          description: A list of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_2'
  /dashboard/activity-log:
    get:
      tags:
      - Dashboard
      summary: Get activity log
      responses:
        "200":
          description: Activity log
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_3'
  /dashboard/settings:
    get:
      tags:
      - Dashboard
      summary: Get settings
      responses:
        "200":
          description: Settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /user:
    get:
      tags:
      - Current user
      summary: Get user profile
      responses:
        "200":
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
    put:
      tags:
      - Current user
      summary: Update user profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_body'
        required: true
      responses:
        "200":
          description: User profile updated
  /contact-us:
    post:
      tags:
      - Contact us
      summary: Contact us form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/contactus_body'
        required: true
      responses:
        "200":
          description: Message sent
  /gdpr/cookies:
    get:
      tags:
      - GDPR
      summary: Get GDPR cookies settings
      responses:
        "200":
          description: GDPR cookies settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /dashboard:
    get:
      tags:
      - Dashboard
      summary: Get basic dashboard data
      responses:
        "200":
          description: Dashboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /waitlist:
    post:
      tags:
      - Marketing
      summary: Join waitlist
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/waitlist_body'
        required: true
      responses:
        "200":
          description: Waitlist entry created
  /marketing-page:
    get:
      tags:
      - Marketing
      summary: Get marketing page content
      responses:
        "200":
          description: Marketing page content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /invite:
    post:
      tags:
      - Marketing
      summary: Invite a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/invite_body'
        required: true
      responses:
        "200":
          description: Invite sent
  /user/data-export:
    get:
      tags:
      - Current user
      summary: Export user data
      responses:
        "200":
          description: User data exported
          content:
            application/json:
              schema:
                type: string
                format: binary
  /dashboard/charts:
    get:
      tags:
      - Dashboard
      summary: Get chart data
      responses:
        "200":
          description: Chart data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
  /content:
    put:
      tags:
      - Blog
      summary: Edit content
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/content_body'
        required: true
      responses:
        "200":
          description: Content updated
  /notifications:
    get:
      tags:
      - Notification
      summary: Get list of notifications
      responses:
        "200":
          description: A list of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_5'
  /blog:
    get:
      tags:
      - Blog
      summary: Get list of blog posts
      responses:
        "200":
          description: A list of blog posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_6'
  /user/invite-link:
    post:
      tags:
      - Current user
      summary: Generate invite link
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_invitelink_body'
        required: true
      responses:
        "200":
          description: Invite link generated
  /dashboard/language-region:
    get:
      tags:
      - Dashboard
      summary: Get language and region settings
      responses:
        "200":
          description: Language and region settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_7'
  /email-templates:
    get:
      tags:
      - Messaging
      summary: Get list of email templates
      responses:
        "200":
          description: A list of email templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_8'
  /email-templates/{id}:
    put:
      tags:
      - Messaging
      summary: Update email template
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/emailtemplates_id_body'
        required: true
      responses:
        "200":
          description: Email template updated
components:
  schemas:
    auth_login_body:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    auth_register_body:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    auth_social_body:
      type: object
      properties:
        provider:
          type: string
        token:
          type: string
    auth_magiclink_body:
      type: object
      properties:
        email:
          type: string
    auth_changepassword_body:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
    messaging_email_body:
      type: object
      properties:
        to:
          type: string
        subject:
          type: string
        body:
          type: string
    payments_stripe_body:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
    payments_flutterwave_body:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
    payments_lemonsqueezy_body:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    inline_response_200_1:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    inline_response_200_2:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
        currency:
          type: string
        status:
          type: string
    inline_response_200_3:
      type: object
      properties:
        id:
          type: integer
        action:
          type: string
        timestamp:
          type: string
    inline_response_200_4:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    user_body:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    contactus_body:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        message:
          type: string
    waitlist_body:
      type: object
      properties:
        email:
          type: string
    invite_body:
      type: object
      properties:
        email:
          type: string
    content_body:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    inline_response_200_5:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        timestamp:
          type: string
    inline_response_200_6:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
    user_invitelink_body:
      type: object
      properties:
        email:
          type: string
    inline_response_200_7:
      type: object
      properties:
        language:
          type: string
        region:
          type: string
    inline_response_200_8:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        html:
          type: string
    emailtemplates_id_body:
      type: object
      properties:
        name:
          type: string
        html:
          type: string
